name: Compile Code

description: 'Creates all code artifacts required to publish a new version.'

inputs:
  version:
    description: 'The current version.'
    type: string
    required: true

runs:
  using: "composite"
  steps:
    - name: Generate new src/version.ts file
      shell: bash
      run: |
        # remove the "v" prefix.
        current_version=$(echo "${{ inputs.version }}" | tr -d 'v')

        echo "export default '$current_version';" > src/version.ts

    - run: npm run compile
      shell: bash
