#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Check if README.md is being pushed
if git diff --name-only HEAD @{push} | grep -q "README.md"; then

  # Get the diff content, removing the meta-headers
  DIFF_CONTENT=$(git diff HEAD @{push} README.md | sed 1,4d)

  # Look for added lines (+) outside the TOC section
  DIFF_CONTENT_EXCLUDING_TOC=$(echo "$DIFF_CONTENT" | sed '/<!-- START doctoc/,/<!-- END doctoc/d' | grep '^\+' || true)

  if [ -n "$DIFF_CONTENT_EXCLUDING_TOC" ]; then
    echo "Changes detected outside TOC section. Running doctoc..."
    npm run doctoc-readme
    git add README.md
    git commit --amend --no-edit
  fi
fi
