name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'
      - name: Install and Build 🔧
        run: npm ci
      - name: Build static storybook files for deploy to GitHub Pages
        run: npm run build-storybook
