name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'
      - name: Install and Build 🔧
        run: npm ci
      - name: Deploy storybook to GitHub Pages
        run: npm run deploy-storybook -- --ci --branch=psl-1242-mvp-storybook-hosting-on-github-pages
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
