name: Spell check

on:
  push:
    branches:
      - '*'
      - '!main'
concurrency:
  group: spell-check-${{ github.head_ref }}
  cancel-in-progress: true
jobs:
  check:
    name: Run spell check
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: '18.13.0'
      - name: Spell check
        run: npx cspell@8.19.4 "**/*.{ts,tsx}"
