name: Test, Build, and Release

on: push
  # push:
  #   branches:
  #     - main

jobs:
  test-storybook:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'
      - name: Install dependencies
        run: npm ci
      - name: Run All Storybook Tests
        run: npm run test-storybook:ci
  build:
    runs-on: ubuntu-latest
    needs: test-storybook
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'
      - name: Install
        run: npm ci
      - name: Build static storybook files for deploy to GitHub Pages
        run: npm run build-storybook
      - name: Generate library bundle ready for publishing
        run: npm run bundle
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: actions@github.com
          message: 'Build library bundle and supporting storybook documentation'
          add: '*'
          commit: --no-verify

  # version-and-release:
  #   runs-on: ubuntu-latest
  #   needs: [test-storybook, build]
  #   env:
  #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #   steps:
  #     - uses: rymndhng/release-on-push-action@master
  #       with:
  #         tag_prefix: "v"
  #         release_name: "Release <RELEASE_TAG>"
