name: Test and Build

on:
  push:
    branches:
      - '*'
      - '!main'
concurrency:
  group: run-tests-and-build-${{ github.head_ref }}
  cancel-in-progress: true     
jobs:
  test-storybook:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: '18.13.0'
      - name: Install dependencies
        run: npm ci
      - name: Run Tests
        run: npm run test-storybook:ci
  test-build-scripts:
    runs-on: ubuntu-latest
    needs: test-storybook
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18.13.0'
      - name: Install
        run: npm ci
      - name: test run build-storybook without error
        run: npm run build-storybook
      - name: test run compile without error
        run: npm run compile