name: Version and Release and build storybook stories 

on:
 push:
    branches:
      - main
jobs:
  build-storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
        node-version: '16.13.0'
      - name: Install
        run: npm ci
      - name: Build static storybook files for deploy to GitHub Pages
        run: npm run build-storybook
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: actions@github.com
          message: 'Build library and supporting storybook documentation'
          add: '*'
          commit: --no-verify
  version-and-release:
    runs-on: ubuntu-latest
    needs: build-storybook
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: rymndhng/release-on-push-action@master
        with:
          tag_prefix: "v"
          bump_version_scheme: norelease
          release_name: "Release <RELEASE_TAG>"